---
- name: Copy and execute script on remote machine
  hosts: rke2_servers
  become: true
  gather_facts: false

  tasks:
    - name: Copy script file to remote machine
      copy:
        src: install_rancher.sh
        dest: /tmp/install_rancher.sh
        mode: '0755'

    - name: Execute script on remote machine
      shell: /tmp/install_rancher.sh
