---
- name: Copy and execute script on remote machine
  hosts: rke2_servers
  become: true
  gather_facts: false

  tasks:
    - name: Copy script file to remote machine
      copy:
        src: install_rancher.sh
        dest: /root/install_rancher.sh
        mode: '0755'

    - name: Execute script on remote machine
      shell:
        cmd: /root/install_rancher.sh
        executable: /bin/bash
        env:
          KUBECONFIG: /etc/rancher/rke2/rke2.yaml
          PATH: /var/lib/rancher/rke2/bin:{{ ansible_env.PATH }}

        
        
