---
- name: Copy and execute script on remote machine
  hosts: rke2_servers
  become: true
  gather_facts: false

  tasks:
    - name: Copy script file to remote machine
      copy:
        src: install_rancher.sh
        dest: /root/install_rancher.sh
        mode: '0755'

    - name: Execute script on remote machine
      command: /root/install_rancher.sh
      args:
        executable: /bin/bash
        environment:
          KUBECONFIG: /etc/rancher/rke2/rke2.yaml
          PATH: "/var/lib/rancher/rke2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
